# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
#  tags:
#    include:
#    - v0.1.*
  branches:
    include:
    - master
    - develop

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

steps:
- task: Docker@1
  displayName: Login
  inputs:
    containerRegistryType: Container Registry
    dockerRegistryEndpoint: docker-hub
    command: login

- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
  displayName: 'Set up the Go workspace'

- script: |
    go get -u github.com/gobuffalo/packr/v2/packr2
    curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
    curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    packr2 --help
  workingDirectory: '$(modulePath)'
  displayName: 'Go Get (Golang Dependencies)'

- script: |
    rm Gopkg.lock || true
    ./bin/goreleaser --rm-dist --debug --config=goreleaser.yml
  workingDirectory: '$(modulePath)'
  displayName: 'Build (GoReleaser)'
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)


